### ISSUE TITLE
Installation now that Influx has rotated keys

### ISSUE THREAD

**Issue by earlthesquirrel** [canique/gateway#1]
I'm having trouble getting basic installation to install.
I believe it's related to influx having to rotate it's keys after the latest Circle CI issue.

FYI, I'm trying to install on a Raspberry Pi 3, B+ with latest 32bit lite install (after running apt-get upgrade...)

Have you tried to test install since this has happened?

**Comment by canique** [comment]
No, I haven't. Good point.
I will check on this today and try to fix the installation for Influx.

I've stumbled upon https://www.influxdata.com/blog/linux-package-signing-key-rotation/ now. This will help me fix it.

**Comment by canique** [comment]
I've commited a fix for this issue.

Try the following:
```
sudo rm -f /etc/apt/sources.list.d/influxdb.list
sudo rm -Rf /tmp/cnq-gateway
```

and then run the installation procedure again starting from step 1.


For existing installations (for customers who have already successfully installed Influx in the past), the fix is to run this command:
`wget -qO- https://repos.influxdata.com/influxdata-archive_compat.key | sudo tee /usr/share/keyrings/influxdb.key`
It will overwrite the existing Influx repository key with the new Influx key. After running this command a `sudo apt-get update` won't show an error with Influx anymore.

**Comment by earlthesquirrel** [comment]
Thanks that fixed that part of my install...
